package com.civil.sods.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.awt.event.ActionListener;

/**
 * @author Omnia Hussein
 * @author Esraa Salah
 * @author Abdullah Salama
 * @author Muhammad Abulmajd
 * @author Muhammad Medhat 
 */

public class InputValuesFrame extends javax.swing.JFrame implements IValuesFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MainFrame
     */
    public InputValuesFrame() {
        initComponents();
        locationColumn();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) (screenSize.getWidth() / 2 - this.getWidth() / 2); 
        int y = (int) (screenSize.getHeight() / 2 - this.getHeight() / 2); 
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPreviousFloorTable = new javax.swing.JButton();
        jFirstFloorTable = new javax.swing.JButton();
        jFloorTableNum = new javax.swing.JTextField();
        jNextFloorTable = new javax.swing.JButton();
        jLastFloorTable = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setTitle("Dimensions and Force Input");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(100.0F);
        jPanel1.setAlignmentY(300.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 425));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 425));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 86, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dimensions and Force Input");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 370));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Col. No.", "Load (N)", "Min. Width (mm)", "Max. Width (mm)", "Min. Length (mm)", "Max. Length (mm)", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 880, 200));

        jPanel6.setBackground(new java.awt.Color(240, 240, 240));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Please Note That You Should Complete All Requested Input Tables To Get Results");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 20));

        jPanel7.setBackground(new java.awt.Color(240, 240, 240));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPreviousFloorTable.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jPreviousFloorTable.setText("‹");
        jPanel7.add(jPreviousFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 30));

        jFirstFloorTable.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jFirstFloorTable.setText("«");
        jPanel7.add(jFirstFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 30));

        jFloorTableNum.setEditable(false);
        jFloorTableNum.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jFloorTableNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFloorTableNum.setText("1");
        jPanel7.add(jFloorTableNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 30));

        jNextFloorTable.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jNextFloorTable.setText("›");
        jPanel7.add(jNextFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 30));

        jLastFloorTable.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLastFloorTable.setText("»");
        jPanel7.add(jLastFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Floor");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 370, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 900, 330));

        jPanel5.setBackground(new java.awt.Color(35, 86, 157));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 950, 20));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setNextFloorTableActionListener(ActionListener listener) {
        jNextFloorTable.addActionListener(listener);
    }

    @Override
    public void setPreviousFloorTableActionListener(ActionListener listener) {
        jPreviousFloorTable.addActionListener(listener);
    }

    @Override
    public void setLastFloorTableActionListener(ActionListener listener) {
        jLastFloorTable.addActionListener(listener);
    }

    @Override
    public void setFirstFloorTableActionListener(ActionListener listener) {
        jFirstFloorTable.addActionListener(listener);
    }

    @Override
    public JTextField getjFloorTableNum() {
        return jFloorTableNum;
    }

    private void locationColumn() {
        JComboBox location = new JComboBox();
        location.addItem("Interior");
        location.addItem("Exterior");
        location.addItem("Corner");
        jTable2.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(location));
    }

    @Override
    public JTable getTable() {
        return jTable2;
    }

    @Override
    public JButton getjFirstFloorTable() {
        return jFirstFloorTable;
    }

    @Override
    public JButton getjLastFloorTable() {
        return jLastFloorTable;
    }

    @Override
    public JButton getjNextFloorTable() {
        return jNextFloorTable;
    }

    @Override
    public JButton getjPreviousFloorTable() {
        return jPreviousFloorTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jFirstFloorTable;
    private javax.swing.JTextField jFloorTableNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLastFloorTable;
    private javax.swing.JButton jNextFloorTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jPreviousFloorTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
