package com.civil.sods.gui;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 * @author Omnia Hussein
 * @author Esraa Salah
 * @author Abdullah Salama
 * @author Muhammad Abulmajd
 * @author Muhammad Medhat
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) (screenSize.getWidth() / 2 - this.getWidth() / 2);
        int y = (int) (screenSize.getHeight() / 2 - this.getHeight() / 2);

        setLocation(new Point(x, y));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel23 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLengthUnit = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jForceUnit = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jConcreteCostPerTon = new javax.swing.JTextField();
        jConcreteCostPerTonUnit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLongitudinalBarCostPerTon = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jStirrupCostPerTon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jOneSpliceCost = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jNumOfFloors = new javax.swing.JTextField();
        jHeightOfFloor = new javax.swing.JTextField();
        jHeightOfFloorUnit = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jNumOfColumns = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jConcreteCover = new javax.swing.JTextField();
        jConcreteCoverUnit = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jYieldStrengthOfSteel = new javax.swing.JComboBox();
        jCharacteristicStrengthOfConcrete = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCharacteristicStrengthOfConcreteUnit = new javax.swing.JLabel();
        jYieldStrengthOfSteelUnit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSpliceType = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jSolve = new javax.swing.JButton();
        jInputValues = new javax.swing.JButton();
        jUsedStirDiameters = new javax.swing.JButton();
        jUsedLongDiameters = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SODS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 86, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("General Inputs");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLengthUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLengthUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "cm", "m" }));
        jPanel3.add(jLengthUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel5.setText("Length unit");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jForceUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jForceUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "KN", "Ton", "Kg" }));
        jPanel3.add(jForceUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 110, -1));
        jForceUnit.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel4.setText("Force unit");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Set Units To Be Used");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 20));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 360, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel15.setText("Concrete cost");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jConcreteCostPerTon.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jConcreteCostPerTon.setText("1000");
        jPanel4.add(jConcreteCostPerTon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 70, 30));

        jConcreteCostPerTonUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jConcreteCostPerTonUnit.setText("unit of cost/m³");
        jPanel4.add(jConcreteCostPerTonUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, 40));

        jLabel17.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel17.setText("Steel cost");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel18.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel18.setText("unit of cost/ton");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 30));

        jLongitudinalBarCostPerTon.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jLongitudinalBarCostPerTon.setText("10000");
        jPanel4.add(jLongitudinalBarCostPerTon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 70, -1));

        jLabel23.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel23.setText("Steel stirrups cost");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        jLabel24.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel24.setText("unit of cost/ton");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 30));

        jStirrupCostPerTon.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jStirrupCostPerTon.setText("10000");
        jPanel4.add(jStirrupCostPerTon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 30));

        jLabel10.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel10.setText("Cost of splice");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jLabel19.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel19.setText("unit of cost/splice");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, 30));

        jOneSpliceCost.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jOneSpliceCost.setText("100");
        jPanel4.add(jOneSpliceCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 70, 30));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Set Each Variable Cost");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 360, 190));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 30, 570));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel13.setText("Floor height");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel14.setText("Number of floors");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jNumOfFloors.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jNumOfFloors.setText("1");
        jPanel6.add(jNumOfFloors, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, -1));

        jHeightOfFloor.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jHeightOfFloor.setText("3000");
        jPanel6.add(jHeightOfFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 60, -1));
        jHeightOfFloor.getAccessibleContext().setAccessibleName("");

        jHeightOfFloorUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jHeightOfFloorUnit.setText("mm");
        jPanel6.add(jHeightOfFloorUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 41, -1, 30));

        jLabel16.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel16.setText("Number of columns in each floor");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jNumOfColumns.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jNumOfColumns.setText("1");
        jPanel6.add(jNumOfColumns, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 60, -1));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Floors Details");
        jPanel14.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 20));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 360, 150));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel21.setText("Concrete cover");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        jConcreteCover.setFont(new java.awt.Font("Ubuntu Condensed", 0, 16)); // NOI18N
        jConcreteCover.setText("30");
        jPanel7.add(jConcreteCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 70, 30));

        jConcreteCoverUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jConcreteCoverUnit.setText("mm");
        jPanel7.add(jConcreteCoverUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 40, 40));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Columns Details");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 360, 90));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jYieldStrengthOfSteel.setEditable(true);
        jYieldStrengthOfSteel.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jYieldStrengthOfSteel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "240", "280", "360", "400" }));
        jYieldStrengthOfSteel.setSelectedIndex(3);
        jPanel8.add(jYieldStrengthOfSteel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jCharacteristicStrengthOfConcrete.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jCharacteristicStrengthOfConcrete.setText("25");
        jPanel8.add(jCharacteristicStrengthOfConcrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel2.setLabelFor(jCharacteristicStrengthOfConcrete);
        jLabel2.setText("Fcu");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 27, 18));

        jCharacteristicStrengthOfConcreteUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jCharacteristicStrengthOfConcreteUnit.setText("N/mm²");
        jPanel8.add(jCharacteristicStrengthOfConcreteUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 60, -1));

        jYieldStrengthOfSteelUnit.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jYieldStrengthOfSteelUnit.setText("N/mm²");
        jPanel8.add(jYieldStrengthOfSteelUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 60, 30));

        jLabel7.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel7.setText("Fy");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Concrete And Steel Characteristics");
        jPanel15.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 20));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 360, 120));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel9.setText("Splices used");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jSpliceType.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jSpliceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lap splice", "Coupler splice", "Weld splice" }));
        jPanel9.add(jSpliceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 40, 150, -1));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Select Used Splice Knot");
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 20));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 360, 80));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSolve.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jSolve.setText("Get Optimum Solution");
        jSolve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jSolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 220, -1));

        jInputValues.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jInputValues.setText("Input Values Window");
        jInputValues.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jInputValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 220, -1));

        jUsedStirDiameters.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jUsedStirDiameters.setText("Used Stirrups Diameters");
        jUsedStirDiameters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jUsedStirDiameters, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, -1));

        jUsedLongDiameters.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jUsedLongDiameters.setText("Used Longitud. Bar Diameters");
        jUsedLongDiameters.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jUsedLongDiameters, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, -1));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Control Panels");
        jPanel19.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel16.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, -1));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Designing System");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 200, 30));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Structure Optimized");
        jPanel16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 200, 30));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 30));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 30));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 730, 130));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 360, 20));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 730, 10));

        jPanel22.setBackground(new java.awt.Color(35, 86, 157));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 780, 20));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that Gets Concrete Cover
     *
     * @return Concrete Cover instance
     */
    public JTextField getjConcreteCover() {
        return jConcreteCover;
    }

    /**
     * Method that Sets Concrete Cover
     *
     * @param jConcreteCover Concrete Cover instance
     *
     */
    public void setjConcreteCover(JTextField jConcreteCover) {
        this.jConcreteCover = jConcreteCover;
    }

    /**
     * Method that Gets Characteristic Strength Of Concrete
     *
     * @return Characteristic Strength Of Concrete
     */
    public JTextField getjCharacteristicStrengthOfConcrete() {
        return jCharacteristicStrengthOfConcrete;
    }

    /**
     * Method that Sets Characteristic Strength Of Concrete
     *
     * @param jCharacteristicStrengthOfConcrete Characteristic Strength Of Concrete instance
     *
     */
    public void setjCharacteristicStrengthOfConcrete(JTextField jCharacteristicStrengthOfConcrete) {
        this.jCharacteristicStrengthOfConcrete = jCharacteristicStrengthOfConcrete;
    }

    /**
     * Method that Gets Height Of Floor
     *
     * @return Height Of Floor
     */
    public JTextField getjHeightOfFloor() {
        return jHeightOfFloor;
    }

    /**
     * Method that Sets Height Of Floor
     *
     * @param jHeightOfFloor Height Of Floor instance
     *
     */
    public void setjHeightOfFloor(JTextField jHeightOfFloor) {
        this.jHeightOfFloor = jHeightOfFloor;
    }

    /**
     * Method that Gets One Splice Cost
     *
     * @return One Splice Cost
     */
    public JTextField getjOneSpliceCost() {
        return jOneSpliceCost;
    }

    /**
     * Method that Sets One Splice Cost
     *
     * @param jOneSpliceCost One Splice Cost instance
     *
     */
    public void setjOneSpliceCost(JTextField jOneSpliceCost) {
        this.jOneSpliceCost = jOneSpliceCost;
    }

    /**
     * Method that Gets Concrete Cost Per Ton
     *
     * @return Concrete Cost Per Ton
     */
    public JTextField getjConcreteCostPerTon() {
        return jConcreteCostPerTon;
    }

    /**
     * Method that Sets Concrete Cost Per Ton
     *
     * @param jConcreteCostPerTon Concrete Cost Per Ton instance
     */
    public void setjConcreteCostPerTon(JTextField jConcreteCostPerTon) {
        this.jConcreteCostPerTon = jConcreteCostPerTon;
    }

    /**
     * Method that Gets Longitudinal Bars Cost Per Ton
     *
     * @return Longitudinal Bars Cost Per Ton
     */
    public JTextField getjLongitudinalBarCostPerTon() {
        return jLongitudinalBarCostPerTon;
    }

    /**
     * Method that Sets Longitudinal Bars Cost Per Ton
     *
     * @param jLongitudinalBarCostPerTon Longitudinal Bars Cost Per Ton instance
     */
    public void setjLongitudinalBarCostPerTon(JTextField jLongitudinalBarCostPerTon) {
        this.jLongitudinalBarCostPerTon = jLongitudinalBarCostPerTon;
    }

    /**
     * Method that Gets Stirrup Cost Per Ton
     *
     * @return Stirrup Cost Per Ton
     */
    public JTextField getjStirrupCostPerTon() {
        return jStirrupCostPerTon;
    }

    /**
     * Method that Sets Stirrup Cost Per Ton
     *
     * @param jStirrupCostPerTon Stirrup Cost Per Ton instance
     *
     */
    public void setjStirrupCostPerTon(JTextField jStirrupCostPerTon) {
        this.jStirrupCostPerTon = jStirrupCostPerTon;
    }

    /**
     * Method that Gets Yield Strength Of Steel
     *
     * @return Yield Strength Of Steel
     */
    public JComboBox getjYieldStrengthOfSteel() {
        return jYieldStrengthOfSteel;
    }

    /**
     * Method that Sets Yield Strength Of Steel
     *
     * @param jYieldStrengthOfSteel Yield Strength Of Steel instance
     *
     */
    public void setjYieldStrengthOfSteel(JComboBox jYieldStrengthOfSteel) {
        this.jYieldStrengthOfSteel = jYieldStrengthOfSteel;
    }

    /**
     * Method that Sets Solve Button Action Listener
     *
     * @param listener Listener instance
     *
     */
    public void setSolveButtonActionListener(ActionListener listener) {
        jSolve.addActionListener(listener);
    }

    /**
     * Method that Sets Force Unit Action Listener
     *
     * @param listener Listener instance
     *
     */
    public void setForceUnitActionListener(ActionListener listener) {
        jForceUnit.addActionListener(listener);
    }

    /**
     * Method that Sets Length Unit Action Listener
     *
     * @param listener Listener instance
     *
     */
    public void setLengthUnitActionListener(ActionListener listener) {
        jLengthUnit.addActionListener(listener);
    }

    /**
     * Method that Sets Input Values Action Listener
     *
     * @param listener Listener instance
     *
     */
    public void setInputValuesActionListener(ActionListener listener) {
        jInputValues.addActionListener(listener);
    }

    /**
     * Method that Gets Characteristics Strength Of Concrete Unit
     *
     * @return Characteristics Strength Of Concrete Unit
     */
    public JLabel getjCharacteristicStrengthOfConcreteUnit() {
        return jCharacteristicStrengthOfConcreteUnit;
    }

    /**
     * Method that Sets Characteristics Strength Of Concrete Unit
     *
     * @param jCharacteristicStrengthOfConcreteUnit Characteristics Strength Of Concrete Unit instance
     *
     */
    public void setjCharacteristicStrengthOfConcreteUnit(JLabel jCharacteristicStrengthOfConcreteUnit) {
        this.jCharacteristicStrengthOfConcreteUnit = jCharacteristicStrengthOfConcreteUnit;
    }

    /**
     * Method that Gets Concrete Cost Per Ton Unit
     *
     * @return Concrete Cost Per Ton Unit
     */
    public JLabel getjConcreteCostPerTonUnit() {
        return jConcreteCostPerTonUnit;
    }

    /**
     * Method that Sets Concrete Cost Per Ton Unit
     *
     * @param jConcreteCostPerTonUnit Concrete Cost Per Ton Unit instance
     *
     */
    public void setjConcreteCostPerTonUnit(JLabel jConcreteCostPerTonUnit) {
        this.jConcreteCostPerTonUnit = jConcreteCostPerTonUnit;
    }

    /**
     * Method that Gets Concrete Cover Unit
     *
     * @return Concrete Cover Unit
     */
    public JLabel getjConcreteCoverUnit() {
        return jConcreteCoverUnit;
    }

    /**
     * Method that Sets Concrete Cover Unit
     *
     * @param jConcreteCoverUnit Concrete Cover Unit instance
     *
     */
    public void setjConcreteCoverUnit(JLabel jConcreteCoverUnit) {
        this.jConcreteCoverUnit = jConcreteCoverUnit;
    }

    /**
     * Method that Gets Height Of Floor Unit
     *
     * @return Height Of Floor Unit
     */
    public JLabel getjHeightOfFloorUnit() {
        return jHeightOfFloorUnit;
    }

    /**
     * Method that Sets Height Of Floor Unit
     *
     * @param jHeightOfFloorUnit Height Of Floor Unit instance
     *
     */
    public void setjHeightOfFloorUnit(JLabel jHeightOfFloorUnit) {
        this.jHeightOfFloorUnit = jHeightOfFloorUnit;
    }

    /**
     * Method that Gets Yield Strength Of Steel Unit
     *
     * @return Yield Strength Of Steel Unit
     */
    public JLabel getjYieldStrengthOfSteelUnit() {
        return jYieldStrengthOfSteelUnit;
    }

    /**
     * Method that Sets Yield Strength Of Steel Unit
     *
     * @param jYieldStrengthOfSteelUnit Yield Strength Of Steel Unit instance
     *
     */
    public void setjYieldStrengthOfSteelUnit(JLabel jYieldStrengthOfSteelUnit) {
        this.jYieldStrengthOfSteelUnit = jYieldStrengthOfSteelUnit;
    }

    /**
     * Method that Gets Force Unit Combo Box
     *
     * @return Force Unit
     */
    public JComboBox getjForceUnit() {
        return jForceUnit;
    }

    /**
     * Method that Gets Length Unit Combo Box
     *
     * @return Length Unit
     */
    public JComboBox getjLengthUnit() {
        return jLengthUnit;
    }

    /**
     * Method that Gets Number Of Columns
     *
     * @return Number Of Columns
     */
    public JTextField getjNumOfColumns() {
        return jNumOfColumns;
    }

    /**
     * Method that Gets Number Of Floors
     *
     * @return Number Of Floors
     */
    public JTextField getjNumOfFloors() {
        return jNumOfFloors;
    }

    /**
     * Method that Gets Splice Type Combo Box
     *
     * @return Splice Type
     */
    public JComboBox getjSpliceType() {
        return jSpliceType;
    }

    /**
     * Method that Sets Used Longitudinal Diameters Action Listener
     *
     * @param listener Listener instance
     *
     */
    public void setUsedLongDiametersActionListener(ActionListener listener) {
        jUsedLongDiameters.addActionListener(listener);
    }

    /**
     * Method that Sets Used Stirrup Diameters Action Listener
     *
     * @param listener Listener instance
     *
     */
    public void setUsedStirDiametersActionListener(ActionListener listener) {
        jUsedStirDiameters.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCharacteristicStrengthOfConcrete;
    private javax.swing.JLabel jCharacteristicStrengthOfConcreteUnit;
    private javax.swing.JTextField jConcreteCostPerTon;
    private javax.swing.JLabel jConcreteCostPerTonUnit;
    private javax.swing.JTextField jConcreteCover;
    private javax.swing.JLabel jConcreteCoverUnit;
    private javax.swing.JComboBox jForceUnit;
    private javax.swing.JTextField jHeightOfFloor;
    private javax.swing.JLabel jHeightOfFloorUnit;
    private javax.swing.JButton jInputValues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jLengthUnit;
    private javax.swing.JTextField jLongitudinalBarCostPerTon;
    private javax.swing.JTextField jNumOfColumns;
    private javax.swing.JTextField jNumOfFloors;
    private javax.swing.JTextField jOneSpliceCost;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSolve;
    private javax.swing.JComboBox jSpliceType;
    private javax.swing.JTextField jStirrupCostPerTon;
    private javax.swing.JButton jUsedLongDiameters;
    private javax.swing.JButton jUsedStirDiameters;
    private javax.swing.JComboBox jYieldStrengthOfSteel;
    private javax.swing.JLabel jYieldStrengthOfSteelUnit;
    // End of variables declaration//GEN-END:variables

}
