package com.civil.sods.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.awt.event.ActionListener;

/**
 * @author Omnia Hussein
 * @author Esraa Salah
 * @author Abdullah Salama
 * @author Muhammad Abulmajd
 * @author Muhammad Medhat
 */
public class OutputValuesFrame extends javax.swing.JFrame implements IValuesFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MainFrame
     */
    public OutputValuesFrame() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) (screenSize.getWidth() / 2 - this.getWidth() / 2); 
        int y = (int) (screenSize.getHeight() / 2 - this.getHeight() / 2); 
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFirstFloorTable = new javax.swing.JButton();
        jPreviousFloorTable = new javax.swing.JButton();
        jFloorTableNum = new javax.swing.JTextField();
        jNextFloorTable = new javax.swing.JButton();
        jLastFloorTable = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jExportData = new javax.swing.JButton();
        jExportDxf = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jChooseNumOfModels = new javax.swing.JButton();

        setTitle("Output Values");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 86, 157));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Optimum Solution");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 50));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 30, 460));

        jPanel5.setBackground(new java.awt.Color(35, 86, 157));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 990, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(240, 240, 240));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Optimized Columns Dimensions, Loads, And Reinforcement Ratios");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 930, 20));

        jPanel7.setBackground(new java.awt.Color(240, 240, 240));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Floor");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jFirstFloorTable.setText("«");
        jPanel7.add(jFirstFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 30));

        jPreviousFloorTable.setText("‹");
        jPanel7.add(jPreviousFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 30));

        jFloorTableNum.setEditable(false);
        jFloorTableNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFloorTableNum.setText("1");
        jPanel7.add(jFloorTableNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 30));

        jNextFloorTable.setText("›");
        jPanel7.add(jNextFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 30));

        jLastFloorTable.setText("»");
        jPanel7.add(jLastFloorTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 370, 50));

        jTable2.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Col. No.", "Width(mm)", "Length(mm)", "Compressive Capacity(N)", "Cost", "Reinforc. Ratio(%)", "Longitud. Bars(mm)", "Stirrups (mm)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 910, 210));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 930, 340));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(240, 240, 240));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Export Data To Wanted Type Or Export AutoCad Drawing File");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, 20));

        jExportData.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jExportData.setText("Export Data");
        jPanel8.add(jExportData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 30));

        jExportDxf.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jExportDxf.setText("Export DXF");
        jPanel8.add(jExportDxf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 550, 90));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(240, 240, 240));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Modeling Optimization");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 370, 20));

        jChooseNumOfModels.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jChooseNumOfModels.setText("Choose No. of Models");
        jPanel10.add(jChooseNumOfModels, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 370, 90));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Method that Gets Next Floor Table Action Listener
     *
     * @param listener Listener Instance
     *
     */
    @Override
    public void setNextFloorTableActionListener(ActionListener listener) {
        jNextFloorTable.addActionListener(listener);
    }

    /**
     * Method that Gets Previous Floor Table Action Listener
     *
     * @param listener Listener Instance
     *
     */
    @Override
    public void setPreviousFloorTableActionListener(ActionListener listener) {
        jPreviousFloorTable.addActionListener(listener);
    }

    /**
     * Method that Gets Last Floor Table Action Listener
     *
     * @param listener Listener Instance
     *
     */
    @Override
    public void setLastFloorTableActionListener(ActionListener listener) {
        jLastFloorTable.addActionListener(listener);
    }

    /**
     * Method that Gets First Floor Table Action Listener
     *
     * @param listener Listener Instance
     *
     */
    @Override
    public void setFirstFloorTableActionListener(ActionListener listener) {
        jFirstFloorTable.addActionListener(listener);
    }

    /**
     * Method that Sets Choose Number Of Models Action Listener
     *
     * @param listener Listener Instance
     *
     */
    public void setChooseNumOfModelsActionListener(ActionListener listener) {
        jChooseNumOfModels.addActionListener(listener);
    }

    /**
     * Method that Sets Export Data Action Listener
     *
     * @param listener Listener Instance
     *
     */
    public void setExportDataActionListener(ActionListener listener) {
        jExportData.addActionListener(listener);
    }

    /**
     * Method that Sets Export DXF Action Listener
     *
     * @param listener Listener Instance
     */
    public void setExportDxfActionListener(ActionListener listener) {
        jExportDxf.addActionListener(listener);
    }

    /**
     * Method that Gets Choose Number Of Models Button
     *
     * @return Choose Number Of Models
     */
    public JButton getjChooseNumOfModels() {
        return jChooseNumOfModels;
    }

    /**
     * Method that Gets Floor Table Number
     *
     * @return Floor Table Number
     */
    @Override
    public JTextField getjFloorTableNum() {
        return jFloorTableNum;
    }

    /**
     * Method that Gets Table
     *
     * @return Table instance
     */
    @Override
    public JTable getTable() {
        return jTable2;
    }

    /**
     * Method that Gets First Floor Table
     *
     * @return First Floor Table
     */
    @Override
    public JButton getjFirstFloorTable() {
        return jFirstFloorTable;
    }

    /**
     * Method that Gets Last Floor Table
     *
     * @return Last Floor Table
     */
    @Override
    public JButton getjLastFloorTable() {
        return jLastFloorTable;
    }

    /**
     * Method that Gets Next Floor Table
     *
     * @return Next Floor Table
     */
    @Override
    public JButton getjNextFloorTable() {
        return jNextFloorTable;
    }

    /**
     * Method that Gets Previous Floor Table
     *
     * @return Previous Floor Table
     */
    @Override
    public JButton getjPreviousFloorTable() {
        return jPreviousFloorTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChooseNumOfModels;
    private javax.swing.JButton jExportData;
    private javax.swing.JButton jExportDxf;
    private javax.swing.JButton jFirstFloorTable;
    private javax.swing.JTextField jFloorTableNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLastFloorTable;
    private javax.swing.JButton jNextFloorTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jPreviousFloorTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
